---
name: Install Puppet
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-puppet:
    name: ${{ matrix.collection }} / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-14', 'ubuntu-24.04']
        collection: [ puppet8, puppetcore8, puppetcore9 ]
        include:
          - collection: puppetcore8
            version: "8.21.0"
          - collection: puppetcore9
            version: "9.0.0"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install puppet-agent from ${{ matrix.collection }} collection
        if: ${{ contains(matrix.collection, 'core') }}
        run: sudo bash -x test_install.sh -v ${{ matrix.version }} -c ${{ matrix.collection }} -p ${{ secrets.PUPPET_FORGE_TOKEN_PUBLIC }}
      - name: Install puppet-agent from ${{ matrix.collection }} collection (pre Puppet Core)
        if: ${{ !contains(matrix.collection, 'core') }}
        run: sudo bash -x test_install.sh -v 8.10.0 -c ${{ matrix.collection }}
